//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmineTableEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedmineTableEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap apply_icon {
            get {
                object obj = ResourceManager.GetObject("apply_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Assignee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColAssignedTo {
            get {
                return ResourceManager.GetString("BackgroundColAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColColor {
            get {
                return ResourceManager.GetString("BackgroundColColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundColStatus {
            get {
                return ResourceManager.GetString("BackgroundColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundLinkSentting {
            get {
                return ResourceManager.GetString("BackgroundLinkSentting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link to Assignee に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundLinkToAssignedTo {
            get {
                return ResourceManager.GetString("BackgroundLinkToAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundLinkToNone {
            get {
                return ResourceManager.GetString("BackgroundLinkToNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link to Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundLinkToStatus {
            get {
                return ResourceManager.GetString("BackgroundLinkToStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closed issue link to Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BackgroundLinkToStatusClosed {
            get {
                return ResourceManager.GetString("BackgroundLinkToStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeAny {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Closed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeClosed {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeContains {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateAfter {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Before に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateBefore {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last 2 weeks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateLast2Weeks {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateLast2Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateLastMonth {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In the past に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateLastNDays {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateLastNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateLastWeek {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateNextMonth {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In the next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateNextNDays {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateNextNDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateNextWeek {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Between に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateRange {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateThisMonth {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateThisWeek {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateThisYear {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateToday {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tomorrow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateTomorrow {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yesterday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDateYesterday {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDateYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doesn&apos;t contain に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeDoesnotContain {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeDoesnotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ends with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeEndsWith {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeNone {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt;= に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeNumGreaterEquals {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeNumGreaterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;= に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeNumLessEquals {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeNumLessEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeOpen {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Starts with に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssueStatusCompareTypeStartsWith {
            get {
                return ResourceManager.GetString("enumIssueStatusCompareTypeStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumMyIssuePropertyTypeDiffEstimatedSpent {
            get {
                return ResourceManager.GetString("enumMyIssuePropertyTypeDiffEstimatedSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigned Spent Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumMyIssuePropertyTypeMySpentHours {
            get {
                return ResourceManager.GetString("enumMyIssuePropertyTypeMySpentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumMyIssuePropertyTypeReplyCount {
            get {
                return ResourceManager.GetString("enumMyIssuePropertyTypeReplyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStatusCompareTypeEquals {
            get {
                return ResourceManager.GetString("enumStatusCompareTypeEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Equals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStatusCompareTypeNotEquals {
            get {
                return ResourceManager.GetString("enumStatusCompareTypeNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings are incomplete.
        ///Please implement the settings from the Settings dialog box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errInvalidSettings {
            get {
                return ResourceManager.GetString("errInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open the setting file. Please check it.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgFailedOpenSettingsFile {
            get {
                return ResourceManager.GetString("ErrMsgFailedOpenSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read following issues.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgFailedReadIssues {
            get {
                return ResourceManager.GetString("ErrMsgFailedReadIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to update following issues.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgFailedUpdateIssues {
            get {
                return ResourceManager.GetString("ErrMsgFailedUpdateIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The previous file not found.
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgNotFoundPreviousFile {
            get {
                return ResourceManager.GetString("ErrMsgNotFoundPreviousFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a custom query. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgSelectCustomQuery {
            get {
                return ResourceManager.GetString("ErrMsgSelectCustomQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input the issue id. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgSelectIssueId {
            get {
                return ResourceManager.GetString("ErrMsgSelectIssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the system administrator API key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgSetAdminApiKey {
            get {
                return ResourceManager.GetString("ErrMsgSetAdminApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set redmine settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrMsgSetRemineSetting {
            get {
                return ResourceManager.GetString("ErrMsgSetRemineSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpanderDisplayCondition {
            get {
                return ResourceManager.GetString("ExpanderDisplayCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pivot Table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExpanderPivotTable {
            get {
                return ResourceManager.GetString("ExpanderPivotTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (New) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNew {
            get {
                return ResourceManager.GetString("FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSettingsBackground {
            get {
                return ResourceManager.GetString("FileSettingsBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSettingsChildIssue {
            get {
                return ResourceManager.GetString("FileSettingsChildIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fields to display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSettingsDisplayFIelds {
            get {
                return ResourceManager.GetString("FileSettingsDisplayFIelds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parent Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSettingsParentIssue {
            get {
                return ResourceManager.GetString("FileSettingsParentIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Updated) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileUpdated {
            get {
                return ResourceManager.GetString("FileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterBoolNo {
            get {
                return ResourceManager.GetString("FilterBoolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterBoolYes {
            get {
                return ResourceManager.GetString("FilterBoolYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the number of days. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgInputDate {
            get {
                return ResourceManager.GetString("FilterErrMsgInputDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a whole number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgInputInteger {
            get {
                return ResourceManager.GetString("FilterErrMsgInputInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a issue number of {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgInputIssueNo {
            get {
                return ResourceManager.GetString("FilterErrMsgInputIssueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgInputNumber {
            get {
                return ResourceManager.GetString("FilterErrMsgInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the correct range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgInvalidRange {
            get {
                return ResourceManager.GetString("FilterErrMsgInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project “{0}” has no category. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgNoCategories {
            get {
                return ResourceManager.GetString("FilterErrMsgNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a filter. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgSelectAnyFilter {
            get {
                return ResourceManager.GetString("FilterErrMsgSelectAnyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a value of {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgSelectValue {
            get {
                return ResourceManager.GetString("FilterErrMsgSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a single project to set a category. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterErrMsgSingleProjectForCategory {
            get {
                return ResourceManager.GetString("FilterErrMsgSingleProjectForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterMultiSelection {
            get {
                return ResourceManager.GetString("FilterMultiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    days に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterPostfixDays {
            get {
                return ResourceManager.GetString("FilterPostfixDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;&lt; my projects &gt;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterProjectMine {
            get {
                return ResourceManager.GetString("FilterProjectMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;&lt; me &gt;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterUserMe {
            get {
                return ResourceManager.GetString("FilterUserMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap icons8_select_column_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_select_column_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap icons8_show_on_redmine_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_show_on_redmine_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Open issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IssuesCmdGoToTicket {
            get {
                return ResourceManager.GetString("IssuesCmdGoToTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IssuesCmdUpdateTicket {
            get {
                return ResourceManager.GetString("IssuesCmdUpdateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings of Edit Issue Table have been updated. Do you want to save it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgConfirmToSave {
            get {
                return ResourceManager.GetString("MsgConfirmToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redmine settings are not configured.
        ///Please set them correctly in the settings screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrUnsetRedminSettings {
            get {
                return ResourceManager.GetString("msgErrUnsetRedminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display conditions have not been changed.
        ///
        ///To update the contents of the displayed issues, please execute &quot;Update Contents&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgNoChangeDisplayConditions {
            get {
                return ResourceManager.GetString("MsgNoChangeDisplayConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The issue id and subject are always displayed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgSelectParentFields {
            get {
                return ResourceManager.GetString("MsgSelectParentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap new_icon {
            get {
                object obj = ResourceManager.GetObject("new_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap open_icon {
            get {
                object obj = ResourceManager.GetObject("open_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Custom Query に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueCustomQuery {
            get {
                return ResourceManager.GetString("ParentIssueCustomQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a custom query to specify the parent ticket. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueCustomQueryMsg {
            get {
                return ResourceManager.GetString("ParentIssueCustomQueryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueFilter {
            get {
                return ResourceManager.GetString("ParentIssueFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select filters to specify the parent ticket. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueFilterMsg {
            get {
                return ResourceManager.GetString("ParentIssueFilterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to specify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueHowToSpecify {
            get {
                return ResourceManager.GetString("ParentIssueHowToSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue Id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueIssueId {
            get {
                return ResourceManager.GetString("ParentIssueIssueId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input the issue id of the parent issue. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueIssueIdMsg {
            get {
                return ResourceManager.GetString("ParentIssueIssueIdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get child issues recursively に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueIssueRecoursiveMsg {
            get {
                return ResourceManager.GetString("ParentIssueIssueRecoursiveMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display the parent issue in this list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParentIssueIssueShowParentIssueMsg {
            get {
                return ResourceManager.GetString("ParentIssueIssueShowParentIssueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Issue Table file(*.eit)|*.eit|All file(*.*)|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RedmineTableEditorFileFormat {
            get {
                return ResourceManager.GetString("RedmineTableEditorFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap reload_icon {
            get {
                object obj = ResourceManager.GetObject("reload_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdApply {
            get {
                return ResourceManager.GetString("RibbonCmdApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdNew {
            get {
                return ResourceManager.GetString("RibbonCmdNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdOpen {
            get {
                return ResourceManager.GetString("RibbonCmdOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdSave {
            get {
                return ResourceManager.GetString("RibbonCmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdSaveAs {
            get {
                return ResourceManager.GetString("RibbonCmdSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save to Redmine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdSaveRedmine {
            get {
                return ResourceManager.GetString("RibbonCmdSaveRedmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Freeze Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdSetFrozenColumn {
            get {
                return ResourceManager.GetString("RibbonCmdSetFrozenColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show on Redmine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdShowRedmine {
            get {
                return ResourceManager.GetString("RibbonCmdShowRedmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Contents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonCmdUpdate {
            get {
                return ResourceManager.GetString("RibbonCmdUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Conditions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonGroupCondition {
            get {
                return ResourceManager.GetString("RibbonGroupCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue Table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonGroupTickets {
            get {
                return ResourceManager.GetString("RibbonGroupTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RibbonTabHome {
            get {
                return ResourceManager.GetString("RibbonTabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap save_icon {
            get {
                object obj = ResourceManager.GetObject("save_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap save_redmine_icon {
            get {
                object obj = ResourceManager.GetObject("save_redmine_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap saveas_icon {
            get {
                object obj = ResourceManager.GetObject("saveas_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap splashScreen_tableEditor {
            get {
                object obj = ResourceManager.GetObject("splashScreen_tableEditor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Conditions for child issues に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditions {
            get {
                return ResourceManager.GetString("SubIssueConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColColName {
            get {
                return ResourceManager.GetString("SubIssueConditionsColColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColEnable {
            get {
                return ResourceManager.GetString("SubIssueConditionsColEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColStatus {
            get {
                return ResourceManager.GetString("SubIssueConditionsColStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status (Condition) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColStatusCondition {
            get {
                return ResourceManager.GetString("SubIssueConditionsColStatusCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColSubject {
            get {
                return ResourceManager.GetString("SubIssueConditionsColSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject (Condtion) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColSubjectCondition {
            get {
                return ResourceManager.GetString("SubIssueConditionsColSubjectCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsColTracker {
            get {
                return ResourceManager.GetString("SubIssueConditionsColTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the conditions for the child tickets you wish to display. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SubIssueConditionsMsg {
            get {
                return ResourceManager.GetString("SubIssueConditionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Invalid user) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInvalid {
            get {
                return ResourceManager.GetString("UserInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (No assignee) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserNoAssignee {
            get {
                return ResourceManager.GetString("UserNoAssignee", resourceCulture);
            }
        }
    }
}
