//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibRedminePower.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibRedminePower.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Operation failed due to a conflict. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgConflict {
            get {
                return ResourceManager.GetString("ApiErrMsgConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You do not have access to the specified resource. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgForbidden {
            get {
                return ResourceManager.GetString("ApiErrMsgForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name resolver service could not resolve the host name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgNameResolutionFailure {
            get {
                return ResourceManager.GetString("ApiErrMsgNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified resource cannot be found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgNotFound {
            get {
                return ResourceManager.GetString("ApiErrMsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No response was received during the time-out period for a request. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgTimeout {
            get {
                return ResourceManager.GetString("ApiErrMsgTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are not authenticated–either not authenticated at all or authenticated incorrectly. Please reauthenticate and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgUnauthorized {
            get {
                return ResourceManager.GetString("ApiErrMsgUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApiErrMsgUnexpected {
            get {
                return ResourceManager.GetString("ApiErrMsgUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automatic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameCustomField {
            get {
                return ResourceManager.GetString("DisplayNameCustomField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameIssue {
            get {
                return ResourceManager.GetString("DisplayNameIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameIssueCategory {
            get {
                return ResourceManager.GetString("DisplayNameIssueCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameIssuePriority {
            get {
                return ResourceManager.GetString("DisplayNameIssuePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameIssueStatus {
            get {
                return ResourceManager.GetString("DisplayNameIssueStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameProject {
            get {
                return ResourceManager.GetString("DisplayNameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Membership に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameProjectMembership {
            get {
                return ResourceManager.GetString("DisplayNameProjectMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Query に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameQuery {
            get {
                return ResourceManager.GetString("DisplayNameQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Entry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameTimeEntry {
            get {
                return ResourceManager.GetString("DisplayNameTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Entry Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameTimeEntryActivity {
            get {
                return ResourceManager.GetString("DisplayNameTimeEntryActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameTracker {
            get {
                return ResourceManager.GetString("DisplayNameTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameUser {
            get {
                return ResourceManager.GetString("DisplayNameUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameVersion {
            get {
                return ResourceManager.GetString("DisplayNameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wiki Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayNameWikiPage {
            get {
                return ResourceManager.GetString("DisplayNameWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigned To に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeAssignedTo {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeAuthor {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeCategory {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remain Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeDiffEstimatedSpent {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeDiffEstimatedSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done Ratio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeDoneRatio {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeDoneRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Due Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeDueDate {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estimated Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeEstimatedHours {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeEstimatedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeFixedVersion {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeFixedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   # に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeId {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Assigned Spent Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeMySpentHours {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeMySpentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypePriority {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spent Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeSpentHours {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeSpentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeStartDate {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeStatus {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeSubject {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Estimated Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeTotalEstimatedHours {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeTotalEstimatedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total Spent Hours に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeTotalSpentHours {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeTotalSpentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tracker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumIssuePropertyTypeTracker {
            get {
                return ResourceManager.GetString("enumIssuePropertyTypeTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contains に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStringCompareContains {
            get {
                return ResourceManager.GetString("enumStringCompareContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EndWith に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStringCompareEndWith {
            get {
                return ResourceManager.GetString("enumStringCompareEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStringCompareEquals {
            get {
                return ResourceManager.GetString("enumStringCompareEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartWith に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enumStringCompareStartWith {
            get {
                return ResourceManager.GetString("enumStringCompareStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///
        ///Please check the network status and Redmine connection settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errConfirmRedmineSettings {
            get {
                return ResourceManager.GetString("errConfirmRedmineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The API key you set does not have an access case.
        ///Please specify an API access key that has system administrator privileges. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errForbidden {
            get {
                return ResourceManager.GetString("errForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load activity information page. ({0})
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errGetWebActivity {
            get {
                return ResourceManager.GetString("errGetWebActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login failed.
        ///Please check your user name and password settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errLoginFailed {
            get {
                return ResourceManager.GetString("errLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the web page. 
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errReadWebPage {
            get {
                return ResourceManager.GetString("errReadWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read the web page. ({0})
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errReadWebPageWithStatusCode {
            get {
                return ResourceManager.GetString("errReadWebPageWithStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redmine connection failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string errRedmineConnectionError {
            get {
                return ResourceManager.GetString("errRedmineConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following exception occurred. Would you like to continue running the application?
        ///
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionMsgConfirm {
            get {
                return ResourceManager.GetString("ExceptionMsgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit {0} because a problem has occurred.
        ///
        ///If you were in the process of working on it, the information may have been lost.
        ///We apologize for any inconvenience caused. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExceptionMsgExit {
            get {
                return ResourceManager.GetString("ExceptionMsgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemsAll {
            get {
                return ResourceManager.GetString("ItemsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More colors... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoreColors {
            get {
                return ResourceManager.GetString("MoreColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter search text. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgEnterFilterKeyword {
            get {
                return ResourceManager.GetString("msgEnterFilterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version has been released, so please get the latest version from our site. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrExceedsLimitDate {
            get {
                return ResourceManager.GetString("msgErrExceedsLimitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrRedmineFailedToDelete {
            get {
                return ResourceManager.GetString("msgErrRedmineFailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrRedmineFailedToGet {
            get {
                return ResourceManager.GetString("msgErrRedmineFailedToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get a current user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrRedmineFailedToGetCurrentUser {
            get {
                return ResourceManager.GetString("msgErrRedmineFailedToGetCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrRedmineFailedToPost {
            get {
                return ResourceManager.GetString("msgErrRedmineFailedToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to update {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrRedmineFailedToPut {
            get {
                return ResourceManager.GetString("msgErrRedmineFailedToPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} % に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressBarProgresText {
            get {
                return ResourceManager.GetString("ProgressBarProgresText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Recent colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentColors {
            get {
                return ResourceManager.GetString("RecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Not specified) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsNotSpecified {
            get {
                return ResourceManager.GetString("SettingsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading {0}... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashScreenFooter {
            get {
                return ResourceManager.GetString("SplashScreenFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Standard colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StandardColors {
            get {
                return ResourceManager.GetString("StandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///     Theme colors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeColors {
            get {
                return ResourceManager.GetString("ThemeColors", resourceCulture);
            }
        }
    }
}
